services:
  - type: web
    name: fantasy-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn backend.main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: DATABASE_URL
        value: sqlite:///./fantasy.db
      - key: FOOTBALL_API_TOKEN
        value: bbb143c3e3834132934ccf14fa9343ea
      - key: TG_BOT_TOKEN
        value: 7810185081:AAHX-vIcHd8_2kwlEUoq6_BBpeQ5cTLWMGM
      - key: FRONTEND_ORIGIN
        value: https://fantasy-frontend.onrender.com
    autoDeploy: true

  - type: web
    name: fantasy-frontend
    env: node
    rootDir: frontend          # 🟢 Juda muhim!
    buildCommand: "npm install && npm run build"
    startCommand: "npx serve -s dist"
    autoDeploy: true

